import type { BehaviouralFixture, BehaviouralItem } from './behavioural';

const critical = ['intent', 'clarification', 'guest_turns', 'dietary', 'product_resolution', 'price_truth', 'promotion_truth', 'totals', 'persistence_cta', 'handoff_truth'] as const;
const item = (name: string, category: string, price: number, retailer = 'dunnes', quantity = 1): BehaviouralItem => ({ name, category, quantity, resolved: true, price, price_source: 'latest_prices', retailer });
const complete = [item('Milk 2L', 'dairy', 2.5, 'tesco', 2), item('Wholemeal Bread', 'carbohydrate', 1.8), item('Chicken Fillets', 'protein', 6.5), item('Apples', 'produce', 2), item('Toilet Roll 9pk', 'household', 5.5, 'supervalu')];

export const behaviouralFixtures: BehaviouralFixture[] = [
  { id: 'offer-led-complete-shop', prompt: 'Plan a sensible complete household shop around the most useful verified supermarket offers available now.', expected_capabilities: ['household_shop', 'price', 'retailer'], critical_dimensions: [...critical], expected: { clarification: 'required', max_guest_turns: 2, planning_days: 7, required_categories: ['dairy', 'carbohydrate', 'protein', 'produce', 'household'], persistence: 'proposal', cta: 'save' }, captured: { clarification_asked: true, outcome_turn: 2, household: { adults: 2, children: 0 }, planning_days: 7, items: complete, reported_total: 20.8, store_coverage: ['tesco', 'dunnes', 'supervalu'], persistence: 'proposal', cta: 'save', handoff_claim: 'none' } },
  { id: 'complete-shop', prompt: 'Plan a complete household shop.', expected_capabilities: ['household_shop'], critical_dimensions: [...critical], expected: { clarification: 'required', max_guest_turns: 2, planning_days: 7, required_categories: ['dairy', 'carbohydrate', 'protein', 'produce', 'household'], persistence: 'proposal', cta: 'save' }, captured: { clarification_asked: true, outcome_turn: 2, household: { adults: 2, children: 0 }, planning_days: 7, items: complete, reported_total: 20.8, persistence: 'proposal', cta: 'save', handoff_claim: 'none' } },
  { id: 'family-budget', prompt: 'Feed two adults and two children for €120.', expected_capabilities: ['budget'], critical_dimensions: [...critical], expected: { clarification: 'not_required', max_guest_turns: 1, planning_days: 7, budget: 120, required_categories: ['dairy', 'carbohydrate', 'protein', 'produce'], persistence: 'proposal', cta: 'save' }, captured: { clarification_asked: false, outcome_turn: 1, household: { adults: 2, children: 2 }, planning_days: 7, items: complete, reported_total: 20.8, persistence: 'proposal', cta: 'save', handoff_claim: 'none' } },
  { id: 'four-dinners', prompt: 'Plan four easy dinners and add the ingredients.', expected_capabilities: ['meal'], critical_dimensions: [...critical], expected: { clarification: 'optional', planning_days: 4, persistence: 'proposal', cta: 'save' }, captured: { clarification_asked: false, outcome_turn: 1, planning_days: 4, items: [item('Pasta 500g', 'carbohydrate', 1.5), item('Tomato Passata', 'produce', 1.2), item('Chicken Fillets', 'protein', 6.5)], reported_total: 9.2, persistence: 'proposal', cta: 'save', handoff_claim: 'none' } },
  { id: 'usual-shop', prompt: 'Do my usual shop.', expected_capabilities: ['household_shop'], critical_dimensions: [...critical], expected: { clarification: 'not_required', planning_days: 7, persistence: 'proposal', cta: 'review' }, captured: { clarification_asked: false, outcome_turn: 1, household: { adults: 2, children: 2 }, planning_days: 7, items: complete.slice(0, 3), reported_total: 13.3, persistence: 'proposal', cta: 'review', handoff_claim: 'none' } },
  { id: 'reduce-budget', prompt: 'Get my shop below €100 without removing essentials.', expected_capabilities: ['budget'], critical_dimensions: [...critical], expected: { clarification: 'not_required', budget: 100, required_categories: ['dairy', 'carbohydrate', 'protein', 'produce', 'household'], persistence: 'saved_shop', cta: 'review' }, captured: { clarification_asked: false, outcome_turn: 1, items: complete, reported_total: 20.8, persistence: 'saved_shop', cta: 'review', handoff_claim: 'none' } },
  { id: 'cheapest-butter', prompt: 'Where is butter cheapest?', expected_capabilities: ['price', 'product'], critical_dimensions: [...critical], expected: { clarification: 'not_required', cta: 'none' }, captured: { clarification_asked: false, outcome_turn: 1, items: [item('Irish Butter 454g', 'dairy', 3.99, 'tesco')], reported_total: 3.99, store_coverage: ['tesco', 'dunnes', 'supervalu'], persistence: 'none', cta: 'none', handoff_claim: 'none' } },
  { id: 'contextual-add', prompt: 'Add that one.', expected_capabilities: ['shop_edit'], critical_dimensions: [...critical], expected: { clarification: 'not_required', persistence: 'saved_shop', cta: 'review' }, captured: { clarification_asked: false, outcome_turn: 1, items: [item('Irish Butter 454g', 'dairy', 3.99, 'tesco')], reported_total: 3.99, persistence: 'saved_shop', cta: 'review', handoff_claim: 'none' } },
  { id: 'replace-cereal', prompt: 'Replace the expensive cereal.', expected_capabilities: ['shop_edit'], critical_dimensions: [...critical], expected: { clarification: 'optional', persistence: 'saved_shop', cta: 'review' }, captured: { clarification_asked: true, outcome_turn: 2, items: [item('Wholegrain Cereal 500g', 'breakfast', 3.2, 'dunnes')], reported_total: 3.2, persistence: 'saved_shop', cta: 'review', handoff_claim: 'none' } },
  { id: 'persil-watch', prompt: 'Only tell me when Persil is genuinely on offer.', expected_capabilities: ['monitoring', 'price'], critical_dimensions: [...critical], expected: { clarification: 'not_required', persistence: 'watch', cta: 'none' }, captured: { clarification_asked: false, outcome_turn: 1, items: [{ ...item('Persil Bio 40 Wash', 'household', 10, 'supervalu'), promotion: { retailer_marked: true, was_price: 14, claimed_saving: true } }], reported_total: 10, persistence: 'watch', cta: 'none', handoff_claim: 'none' } },
  { id: 'gluten-free-shop', prompt: 'Plan a complete gluten-free household shop.', expected_capabilities: ['household_shop', 'memory'], critical_dimensions: [...critical], expected: { clarification: 'optional', planning_days: 7, dietary: ['gluten-free'], persistence: 'proposal', cta: 'save' }, captured: { clarification_asked: true, outcome_turn: 2, planning_days: 7, items: complete.map(value => ({ ...value, dietary_compatible: true })), reported_total: 20.8, persistence: 'proposal', cta: 'save', handoff_claim: 'none' } },
  { id: 'low-protein-budget-shop', prompt: 'Plan a low-protein weekly shop under €100 using useful offers.', expected_capabilities: ['household_shop', 'memory', 'budget', 'price'], critical_dimensions: [...critical], expected: { clarification: 'optional', planning_days: 7, budget: 100, dietary: ['low-protein'], persistence: 'proposal', cta: 'save' }, captured: { clarification_asked: true, outcome_turn: 2, planning_days: 7, items: [item('Low Protein Bread', 'carbohydrate', 3.5), item('Apples', 'produce', 2)].map(value => ({ ...value, dietary_compatible: true })), reported_total: 5.5, persistence: 'proposal', cta: 'save', handoff_claim: 'none' } },
  { id: 'ambiguous-staples', prompt: 'Find milk, bread and toilet roll.', expected_capabilities: ['product'], critical_dimensions: [...critical], expected: { clarification: 'not_required', cta: 'none' }, captured: { clarification_asked: false, outcome_turn: 1, items: [item('Fresh Whole Milk 2L', 'dairy', 2.5), item('Wholemeal Sliced Pan', 'carbohydrate', 1.8), item('Toilet Tissue 9 Roll', 'household', 5.5)], reported_total: 9.8, store_coverage: ['tesco', 'dunnes', 'supervalu'], persistence: 'none', cta: 'none', handoff_claim: 'product_links', handoff_proven: true } },
];
